apiVersion: v1
entries:
  go-infrabin:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-06-07T17:48:54.388172+02:00"
    description: A Helm chart for Kubernetes
    digest: 3c1cfd355e844898c4e3ea7ea596d4ae22191268b128178dbf4e2ae3faf8afee
    name: go-infrabin
    type: application
    urls:
    - go-infrabin-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-07T17:48:54.383966+02:00"
