changelog:
  skip: true
# Build customization
builds:
  - main: ./cmd/go-infrabin/main.go
    binary: go-infrabin
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archives:
  - format: tar.gz
