repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/golangci/golangci-lint
  rev: v1.39.0
  hooks:
    - id: golangci-lint
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: helmlint
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.5.0
  hooks:
  - id: helm-docs
    files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
