#
# Example Configuration
#
# Any values left out will take the default supplied within config.go

#http:
#    host: 0.0.0.0
#    port: 8080
#grpc:
#    host: 127.0.0.1
#    port: 60002
#admin:
#    host: 1.2.3.4
#    port: 1337
#prom:
#    host: 0.0.0.0
#    port: 54321