{{- if .Values.rbac.crossAZ.enabled }}
---
# ClusterRole for CrossAZ endpoint - grants access to pods and nodes
# Nodes are cluster-scoped resources requiring ClusterRole
# Pods are namespace-scoped but can be accessed via ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "go-infrabin.fullname" . }}-crossaz
  labels:
    {{- include "go-infrabin.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
# ClusterRoleBinding for the CrossAZ ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "go-infrabin.fullname" . }}-crossaz
  labels:
    {{- include "go-infrabin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "go-infrabin.fullname" . }}-crossaz
subjects:
  - kind: ServiceAccount
    name: {{ include "go-infrabin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
