apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-infrabin.fullname" . }}
  labels:
    {{- include "go-infrabin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.args.serverPort }}
      targetPort: http-service
      protocol: TCP
      name: http-service
    - port: {{ .Values.args.gRPCPort }}
      targetPort: grpc-service
      protocol: TCP
      name: grpc-service
    - port: {{ .Values.args.promPort }}
      targetPort: http-prom
      protocol: TCP
      name: http-prom
  selector:
    {{- include "go-infrabin.selectorLabels" . | nindent 4 }}
