apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-infrabin.fullname" . }}
  labels:
    {{- include "go-infrabin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-service
      protocol: TCP
      name: http
  selector:
    {{- include "go-infrabin.selectorLabels" . | nindent 4 }}
