package main

import (
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"github.com/maruina/go-infrabin/gen/infrabin/v1/infrabinv1connect" // generated by protoc-gen-connect-go
	"github.com/maruina/go-infrabin/internal/server"                   // generated by protoc-gen-go
)

func main() {
	infrabinServer := &server.InfrabinServer{}
	mux := http.NewServeMux()
	path, handler := infrabinv1connect.NewInfrabinServiceHandler(infrabinServer)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
