name: ci
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read
  id-token: 'write'

jobs:
  testlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: make-test
        run: make test && make checkgenerate
      - name: make-lint
        run: make lint
      - name: Build the docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          tags: |
            docker.io/maruina/go-infrabin:latest
            ghcr.io/maruina/go-infrabin:latest

  docker-build-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - testlint
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: maruina/go-infrabin
      - name: Build and push latest docker image on master
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
