name: CodeQL

on:
  pull_request:

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25

      - name: Check out code
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get protoc go binaries
        run: make tools

      - name: Genereate code for infrabin protofile
        run: make protoc

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
