name: CodeQL

on:
  push:
  pull_request:

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Install Protoc
        uses: arduino/setup-protoc@master

      - name: Get dependencies
        run: go mod download

      - name: Get protoc go binaries
        run: |
          go install \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
            google.golang.org/protobuf/cmd/protoc-gen-go \
            google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Genereate code for infrabin protofile
        run: make protoc

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
