name: CodeQL

on:
  push:
  pull_request:

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Install Protoc
        uses: arduino/setup-protoc@master

      - name: Get protoc go binaries
        run: make tools

      - name: Genereate code for infrabin protofile
        run: make protoc

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
